/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 회원가입 (USR-001)
         * @description ⚠️ 1차: 이메일 인증은 미구현. 메일 발송 인프라 결정 후 추가.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 로그인 (USR-002)
         * @description JWT 액세스(30분) + 리프레시(14일) 발급. 5회 실패 잠금은 후속 작업.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 목록 조회
         * @description ON_SALE 상태 상품. categoryId 지정 시 해당 분류로 필터.
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{productId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상품 리뷰 목록 */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{productId}/reviews/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상품 리뷰 요약 (평균/개수) */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{productId}/qna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 Q&A 트리 조회
         * @description 질문(최신순) + 각 질문의 답변. 비밀글은 작성자 본인에게만 본문 노출.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 상세 조회
         * @description 기본 정보 + 용지×크기 단가 매트릭스 (paperOptions). AI_ENTRY/CUSTOM_ENTRY 는 paperOptions 가 비어있고, 가격은 별도 price_rule 로 계산.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 활성 용지 + 크기 칩 전체 조회
         * @description 용지 4종(백색/투명/의류/판박이)과 각 용지에 매핑된 크기 칩 목록을 함께 반환. 편집기/주문 옵션 단계에서 사용.
         */
        get: operations["listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operation/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 홈 섹션 타이틀 조회 (ADM-003) */
        get: operations["listSections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operation/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공개 설정값 조회
         * @description GA4 측정 ID, 무료 재생성 횟수 등 클라이언트에서 참고할 값. prefix로 키 prefix 필터 가능 (예: prefix=editor).
         */
        get: operations["listConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operation/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 활성 배너 조회
         * @description type=TOP (홈 상단 배너) 또는 STRIP (중간 띠 배너). 노출 기간 조건 자동 적용.
         */
        get: operations["listBanners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서비스 상태 확인
         * @description 프론트/모니터링이 호출하는 단순 OK 응답.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 디자인 그룹 전체 조회
         * @description 디모 보유 디자인 대분류 (디모프렌즈, 베이비 베어 등). 커스텀 편집기 진입 시 사용.
         */
        get: operations["listGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs/groups/{groupId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 특정 디자인 그룹의 세부 디자인 조회 */
        get: operations["listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용 가능한 서체 전체 조회
         * @description 손글씨체/튼튼체/반듯체/동글체 등. 일반 스티커에서는 디자인별 허용 서체로 추가 필터링.
         */
        get: operations["listFonts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내부 상품 분류 전체 조회
         * @description 디자인/심플(상호배타) + 방수/의류/UV DTF/판박이 등(중복허용). 관리자/필터 용도.
         */
        get: operations["listProductCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전시 카테고리 조회
         * @description ui_type(tab/icon/section)별로 정렬된 활성 전시 카테고리.
         */
        get: operations["listDisplayCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 이메일 회원가입 요청 */
        SignupRequest: {
            email: string;
            password: string;
            nickname: string;
            marketingAgree?: boolean;
        };
        /** @description 내 정보 응답 */
        MeResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            nickname?: string;
            phone?: string;
            marketingAgree?: boolean;
        };
        /** @description 이메일 로그인 요청 */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description 토큰 응답 */
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExpiresInSec?: number;
        };
        PageProductResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProductResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
        };
        /** @description 상품 목록/카드 응답 */
        ProductResponse: {
            /** Format: int64 */
            id?: number;
            /**
             * @description GENERAL | CUSTOM_ENTRY | AI_ENTRY
             * @enum {string}
             */
            type?: "GENERAL" | "CUSTOM_ENTRY" | "AI_ENTRY";
            name?: string;
            /** Format: int64 */
            productCategoryId?: number;
            /** Format: int64 */
            designItemId?: number;
            /** Format: int32 */
            basePrice?: number;
            thumbnailUrl?: string;
            /** @enum {string} */
            status?: "ON_SALE" | "HIDDEN" | "SOLD_OUT";
            /** Format: int32 */
            sort?: number;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        PageProductReviewDto: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProductReviewDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        /** @description 상품 리뷰 응답 */
        ProductReviewDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: int32 */
            rating?: number;
            body?: string;
            authorName?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 상품 리뷰 요약 (평균 평점 + 개수) */
        ProductReviewSummary: {
            /** Format: int64 */
            count?: number;
            /** Format: double */
            averageRating?: number;
        };
        /** @description 상품 Q&A — 질문 1건 + 답변 N건 */
        ProductQnaDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            productId?: number;
            /**
             * @description QUESTION | ANSWER
             * @enum {string}
             */
            type?: "QUESTION" | "ANSWER";
            secret?: boolean;
            /** @description 비밀글이면 본문은 마스킹되어 빈 문자열 */
            body?: string;
            authorName?: string;
            /** Format: date-time */
            createdAt?: string;
            answers?: components["schemas"]["ProductQnaDto"][];
        };
        /** @description 용지×크기 단가 (ORD-001 실시간 계산용) */
        PaperOption: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            paperTypeId?: number;
            paperCode?: string;
            paperName?: string;
            /** Format: int64 */
            paperSizeId?: number;
            sizeLabel?: string;
            widthMm?: number;
            heightMm?: number;
            /** Format: int32 */
            unitPrice?: number;
        };
        /** @description 상품 상세 응답 */
        ProductDetailResponse: {
            /** Format: int64 */
            id?: number;
            /**
             * @description GENERAL | CUSTOM_ENTRY | AI_ENTRY
             * @enum {string}
             */
            type?: "GENERAL" | "CUSTOM_ENTRY" | "AI_ENTRY";
            name?: string;
            /** Format: int64 */
            productCategoryId?: number;
            /** Format: int64 */
            designItemId?: number;
            /** Format: int32 */
            basePrice?: number;
            thumbnailUrl?: string;
            /** @description 상세 페이지 HTML (마케팅/소개 컨텐츠) */
            detailHtml?: string;
            /** @description 상세 페이지 추가 이미지 URL 배열 */
            detailImages?: string[];
            /** @enum {string} */
            status?: "ON_SALE" | "HIDDEN" | "SOLD_OUT";
            /** Format: int32 */
            sort?: number;
            paperOptions?: components["schemas"]["PaperOption"][];
        };
        /** @description 용지 + 크기 칩 응답 */
        PaperTypeResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /**
             * @description white | clear | clothing | transfer
             * @example white
             */
            code?: string;
            /** @example 백색 */
            name?: string;
            /** @example 선명한 인쇄. 어디에나 잘 어울려요 */
            hoverDesc?: string;
            sampleImageUrl?: string;
            /** Format: int32 */
            sort?: number;
            sizes?: components["schemas"]["SizeChip"][];
        };
        SizeChip: {
            /** Format: int64 */
            id?: number;
            label?: string;
            widthMm?: number;
            heightMm?: number;
            /** Format: int32 */
            sort?: number;
        };
        SectionTitle: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            sectionKey?: string;
            title?: string;
            /** Format: int32 */
            sort?: number;
            active?: boolean;
        };
        AppConfig: {
            /** Format: int64 */
            id?: number;
            configKey?: string;
            valueStr?: string;
            description?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Banner: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "TOP" | "STRIP";
            title?: string;
            imageUrl?: string;
            linkUrl?: string;
            ctaText?: string;
            /** Format: int32 */
            sort?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            active?: boolean;
        };
        DesignGroup: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            designSimpleCategoryId?: number;
            /** Format: int32 */
            sort?: number;
            active?: boolean;
        };
        DesignItem: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            designGroupId?: number;
            name?: string;
            imageUrl?: string;
            /** @enum {string} */
            namePositionType?: "FIXED" | "SELECTABLE";
            /** @enum {string} */
            fixedNamePosition?: "BOTTOM" | "RIGHT";
            /** Format: int32 */
            sort?: number;
            active?: boolean;
        };
        Font: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            code?: string;
            name?: string;
            assetUrl?: string;
            /** Format: int32 */
            sort?: number;
            active?: boolean;
        };
        ProductCategory: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            code?: string;
            name?: string;
            /** @enum {string} */
            kind?: "DESIGN_SIMPLE" | "USAGE";
            active?: boolean;
        };
        DisplayCategory: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            uiType?: "TAB" | "ICON" | "SECTION";
            /** Format: int32 */
            sort?: number;
            /** Format: int64 */
            bannerId?: number;
            active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                categoryId?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageProductResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageProductReviewDto"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductReviewSummary"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductQnaDto"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductDetailResponse"];
                };
            };
        };
    };
    listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaperTypeResponse"][];
                };
            };
        };
    };
    listSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionTitle"][];
                };
            };
        };
    };
    listConfigs: {
        parameters: {
            query?: {
                prefix?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppConfig"][];
                };
            };
        };
    };
    listBanners: {
        parameters: {
            query?: {
                type?: "TOP" | "STRIP";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Banner"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DesignGroup"][];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DesignItem"][];
                };
            };
        };
    };
    listFonts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Font"][];
                };
            };
        };
    };
    listProductCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductCategory"][];
                };
            };
        };
    };
    listDisplayCategories: {
        parameters: {
            query?: {
                uiType?: "TAB" | "ICON" | "SECTION";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DisplayCategory"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
}
